### PR TITLE
+ Add hex and binary support to poke values. Partially addresses #2.

### LINKED ISSUE #2: Allow hexadecimal and binary input for values in PEEK and POKE

### PR DESCRIPTION
**Pull request by AndreasOM**
Added some very simple code to allow non decimal formats for the poke `value`.
Added an explicit clap parser to catch wrong values earlier.
Kept it super light, but if you like it you can spread it to the other arguments as well.

Don't have my ultimate here, so blind fix.

### CODE REVIEW

**Comment by mlund** [comment]
Nice! I guess we could do the same for `address` and get rid of the `parse_int` dependency.

**Comment by mlund** [comment]
Closes #3

**Comment by AndreasOM** [comment]
Just say the word, and I can do it for all args.

**Comment by mlund** [comment]
> Just say the word, and I can do it for all args.

Thanks a lot, that would be great.

**Comment by AndreasOM** [comment]
Ah, sorry. Had this sitting on my disk, and forgot to push.
https://github.com/AndreasOM/ultimate64/tree/hex-and-binary-args

Feel free to ignore.

**Comment by mlund** [comment]
Thanks! It's probably best to let `parse_int` do the conversion. Would you happen have experience with http posting to add disk image support (see #5?).

**Pull request merged**
